[tool.poetry]
name = "pidgeon-probe"
version = "0.1.0"
description = "Pidgeon probe"
authors = ["Hrvoje JuriÄ‡ <hrvoje@altibiz.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
