format = """\
[╭─](bold bright-cyan)\
$username[@](bold bright-cyan)$hostname \
[\\(](bold bright-cyan)$localip[\\)](bold bright-cyan) \
[using](white italic) $shlvl[$shell](bold dimmed red)\

$aws\
$azure\
$gcloud\
$openstack\
$singularity\

$container\
$docker_context\
$kubernetes\
$terraform\

$nix_shell\
$helm\
$conda\
$cmake\

$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$vagrant\
$zig\
$crystal\

$jobs\
$time\
$cmd_duration\
$status\

$battery\
$memory_usage\

$line_break\

[│](bold cyan) \
$package\
[in](white italic) $directory$vcsh\
$git_branch$hg_branch\
$git_commit$git_state$git_metrics$git_status\
$time\
$line_break\

[╰─](bold dimmed cyan)\
"""

scan_timeout = 500
command_timeout = 500
add_newline = true

[username]
format = "[$user]($style)"
style_user = "bold bright-purple"
style_root = "bold bright-red"
show_always = true

[hostname]
format = "[$hostname]($style)"
style = "bold purple"
trim_at = "-"
ssh_only = false
disabled = false

[localip]
format = "[$localipv4]($style)"
style = "bold purple"
disabled = false

[shell]
fish_indicator = "󰈺 "
bash_indicator = " "
style ="10 bold"
disabled = false

[shlvl]
threshold = 2
format = "[$symbol]($style) "
symbol = ""
repeat = true
style = "dimmed yellow"
disabled = false

[aws]
symbol = " "

[azure]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[container]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[cmake]
symbol = " "

[lua]
symbol = " "

[cmd_duration]
min_time = 1
format = "[took](white italic) [$duration]($style)"
disabled = false
style = "underline bold bright-yellow"

[status]
symbol = " "
style = "bright red"
format = """ \
[[{](bold cyan)\
$symbol\
$status_common_meaning\
$status_signal_name\
$status_maybe_int\
[}](bold cyan)]\
($style)"""
map_symbol = true
disabled = false

[package]
symbol = "󰏗 "
format ="[$symbol$version]($style)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[on](italic dimmed white) [$symbol $branch]($style)"
style = "bold blue"
symbol = ""

[hg_branch]
format = "[on](italic dimmed white) [$symbol $branch]($style)"
style = "bold blue"
symbol = ""

[git_status]
style = "bold bright-yellow"
format = """ \
[[{](bold cyan)\
$all_status\
$ahead_behind\
[}](bold cyan)]\
($style)"""
ahead = "${count}"
diverged = "󰹺${ahead_count}${behind_count}"
behind = "${count}"
deleted = "x"

[character]
success_symbol = "[󰞷 ](bold green)"
vicmd_symbol = "[ ](bold green)"
error_symbol = "[ ](bold bright-red)"

[[battery.display]]
threshold = 20
